Server validation with environment override strategy

diff --git a/projects/multi-services-node/server b/projects/multi-services-node/server
--- a/projects/multi-services-node/server
+++ b/projects/multi-services-node/server
@@ -1,8 +1,5 @@
 #/bin/bash
 
-# Default name for the project environment file
-#ENV_FILE=.env
-
 hash () {
     [[ $(which md5) ]] && HASH_CMD=md5 || HASH_CMD=md5sum
     echo $1 | $HASH_CMD
@@ -41,6 +38,7 @@ CONFIG_FILE="$SCRIPT_NAME.yml"
 
 
 # Validate Environment Configuration
+# -- to be completed --
 if [ ! -f $CONFIG_FILE ]; then
 
     if [ $(which wget) ] ; then
@@ -52,13 +50,13 @@ if [ ! -f $CONFIG_FILE ]; then
     echo ""
     echo "============== WARNING ==============="
     echo ""
-    echo "  !!! >> $ENV_FILE << file is missing !!!"
+    echo "  !!! >> $CONFIG_FILE << file is missing !!!"
     echo ""
     echo "You need to provide a small configuration to run this proxy :-)"
-    echo "Please run the following command:"
-    echo ""
-    echo "    printf 'SERVER_IP=$PUBLIC_IP\nSERVER_PORT=80' > $ENV_FILE"
-    echo ""
+    #echo "Please run the following command:"
+    #echo ""
+    #echo "    printf 'proxy:P=$PUBLIC_IP\nSERVER_PORT=80' > $ENV_FILE"
+    #echo ""
     echo "======================================"
     echo ""
     exit 1
@@ -91,8 +89,8 @@ fi
 #
 
 if [[ "up" == $PROJECT_CMD ]]; then
-    #$SCRIPT_PATH config validate
-    #[[ $? == 1 ]] && exit $?
+    $SCRIPT_PATH config validate
+    [[ $? == 1 ]] && exit $?
     $SCRIPT_PATH config generate
     $SCRIPT_PATH proxy up -d
     $SCRIPT_PATH compose up -d
@@ -118,8 +116,8 @@ if [[ "down" == $PROJECT_CMD ]]; then
 fi
 
 if [[ "reload" == $PROJECT_CMD ]]; then
-    #$SCRIPT_PATH config validate
-    #[[ $? == 1 ]] && exit $?
+    $SCRIPT_PATH config validate
+    [[ $? == 1 ]] && exit $?
     $SCRIPT_PATH proxy stop
     $SCRIPT_PATH config generate
     $SCRIPT_PATH proxy up -d
@@ -138,14 +136,16 @@ if [[ "config" == $PROJECT_CMD ]]; then
             [[ -f $APP_OVERRIDE_FILE ]] && rm $APP_OVERRIDE_FILE
 
             # Overriddable Variables
-            eval APP_PORT=\$"services__${APP_NAME}__port"
-            eval APP_HOST=\$"services__${APP_NAME}__host"
+            eval APP_ENV=\$"apps__${APP_NAME}__env"
+            eval APP_PORT=\$"apps__${APP_NAME}__port"
+            eval APP_HOST=\$"apps__${APP_NAME}__host"
 
             APP_OVERRIDE=""
+            [[ $APP_ENV != "" ]] && APP_OVERRIDE="$APP_OVERRIDE""PROJECT_ENV=$APP_ENV "
             [[ $APP_PORT != "" ]] && APP_OVERRIDE="$APP_OVERRIDE""PROJECT_PORT=$APP_PORT "
             [[ $APP_HOST != "" ]] && APP_OVERRIDE="$APP_OVERRIDE""PROJECT_HOST=$APP_HOST "
 
-            echo $APP_OVERRIDE | tr ' ' '\n' > $APP_OVERRIDE_FILE
+            [[ $APP_OVERRIDE != "" ]] && echo $APP_OVERRIDE | tr ' ' '\n' > $APP_OVERRIDE_FILE
         done
 
         # Static files
@@ -167,8 +167,8 @@ if [[ "config" == $PROJECT_CMD ]]; then
             cp $TEMPLATES_ROOT/virtual-host.conf.tpl $CONFIG_FILE_TMP
             sed -i -e "s/\$SERVER_IP/$proxy__ip/g" $CONFIG_FILE_TMP
             sed -i -e "s/\$SERVER_PORT/$proxy__port/g" $CONFIG_FILE_TMP
-            (cd $d && source .env && source .env.override && sed -i -e "s/\$PROJECT_HOST/$PROJECT_HOST/g" $CONFIG_FILE_TMP)
-            (cd $d && source .env && source .env.override && sed -i -e "s/\$PROJECT_PORT/$PROJECT_PORT/g" $CONFIG_FILE_TMP)
+            (cd $d && [ -f .env ] && source .env && [ -f .env.override ] && source .env.override && sed -i -e "s/\$PROJECT_HOST/$PROJECT_HOST/g" $CONFIG_FILE_TMP)
+            (cd $d && [ -f .env ] && source .env && [ -f .env.override ] && source .env.override && sed -i -e "s/\$PROJECT_PORT/$PROJECT_PORT/g" $CONFIG_FILE_TMP)
             cat $CONFIG_FILE_TMP > $CONFIG_FILE
         done
         exit 0
@@ -178,13 +178,23 @@ if [[ "config" == $PROJECT_CMD ]]; then
         PORTS=""
         for d in apps/*/ ; do
             APP_NAME=$(basename "$d")
-            APP_PORT=$(cd $d && source .env && echo $PROJECT_PORT)
+
+            APP_PORT_DEFAULT=$(cd $d && [ -f .env ] && source .env && echo $PROJECT_PORT)
+            eval APP_PORT_OVERRIDE=\$"apps__${APP_NAME}__port"
+            APP_PORT=${APP_PORT_OVERRIDE:-$APP_PORT_DEFAULT}
+
             if [[ $PORTS == *"$APP_PORT;"* ]]; then
                 echo ""
                 echo "====== PORT CONFLICT DETECTED ======"
                 echo ""
-                echo $PORTS | tr ';' '\n'
+                echo ${PORTS%?} | tr ';' '\n'
                 echo "$APP_NAME -> $APP_PORT << Check this!"
+                echo ""
+                if [[ $APP_PORT == $APP_PORT_OVERRIDE ]]; then
+                    echo "(looks like a \"$CONFIG_FILE\" error)"
+                else
+                    echo "(looks like a \"$d.env\" error)"
+                fi
                 echo "===================================="
                 echo ""
                 exit 1
@@ -195,13 +205,24 @@ if [[ "config" == $PROJECT_CMD ]]; then
         HOSTS=""
         for d in apps/*/ ; do
             APP_NAME=$(basename "$d")
-            APP_HOST=$(cd $d && source .env && echo $PROJECT_HOST)
-            if [[ $HOSTS == *"$APP_HOST;"* ]]; then
+
+            APP_HOST_DEFAULT=$(cd $d && [ -f .env ] && source .env && echo $PROJECT_HOST)
+            eval APP_HOST_OVERRIDE=\$"apps__${APP_NAME}__host"
+            APP_HOST_OVERRIDE=${APP_HOST_OVERRIDE:-$APP_NAME}
+            APP_HOST=${APP_HOST_OVERRIDE:-$APP_HOST_DEFAULT}
+
+            if [[ $HOSTS == *"$APP_HOST"* ]]; then
                 echo ""
                 echo "====== HOST CONFLICT DETECTED ======"
                 echo ""
-                echo $HOSTS | tr ';' '\n'
+                echo ${HOSTS%?} | tr ';' '\n'
                 echo "$APP_NAME -> $APP_HOST << Check this!"
+                echo ""
+                if [[ $APP_HOST == $APP_HOST_OVERRIDE ]]; then
+                    echo "(looks like a \"$CONFIG_FILE\" error)"
+                else
+                    echo "(looks like a \"$d.env\" error)"
+                fi
                 echo "===================================="
                 echo ""
                 exit 1
